"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let Program = "Hello world";
let Author = "John Smith";
let Date = "July 10,2023";
let Description = "this program print the message 'Hello world!' to the console";
console.log("Hello World");
let program = "calculate cirdcle area";
let Autho = "John Doe";
let Dat = "July 10,2023";
let Descriptio = "This program calcuates the area of a circle given its redius";
let radius = 5;
const pi = 3.14;
let area = pi * radius * radius;
console.log("the area of the circile is:", area);
